name: CI
env:
  APPLICATION_NAME : svb_hack
  PROJECT_NAME: "scb"
  STAGE: "dev"
  VERSION: "ver-${{ github.sha }}"
  V: "1.0"
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:

  deploy:
    runs-on: ubuntu-latest
    env:
      WORK_DIR: "/home/${{ secrets.USERNAME }}/deploy/sovcombank_hakaton/"
    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ env.WORK_DIR }}
            git checkout dev
            git pull
            docker-compose -f down
            docker container rm ${{ env.PROJECT_NAME }}-nginx
            docker container rm ${{ env.PROJECT_NAME }}-backend
            docker container rm ${{ env.PROJECT_NAME }}-postgres
            docker rmi ${{ env.PROJECT_NAME}} -f
            docker-compose -f up --force-recreate -d
